# Generated by Django 5.0.1 on 2024-02-05 14:49

import uuid
from django.db import migrations, models
from django.core.management import call_command

def load_data(apps, schema_editor):
    call_command('loaddata', 'propriedades_seed.json')

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Propriedades',
            fields=[
                ('idPropriedade', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nomePropriedade', models.CharField(max_length=255)),
                ('numeroCar', models.CharField(max_length=255)),
                ('uf', models.CharField(max_length=255)),
                ('municipio', models.CharField(max_length=255)),
                ('pais', models.CharField(max_length=255)),
                ('status', models.BooleanField(default=True)),
                ('liberado', models.IntegerField(choices=[(0, 'Bloqueado'), (1, 'Liberado'), (2, 'Alerta')], default=0, verbose_name='liberado')),
            ],
            options={
                'db_table': 'Propriedades',
            },
        ),
        migrations.RunPython(load_data),
    ]
