# Generated by Django 5.0.1 on 2024-02-05 23:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnaliseHistorico',
            fields=[
                ('dateAnalise', models.DateField()),
                ('idAnaliseHistorico', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nomePropriedade', models.CharField(max_length=255)),
                ('numeroCar', models.CharField(max_length=14)),
            ],
            options={
                'db_table': 'AnaliseHistorico',
            },
        ),
    ]
