# Generated by Django 5.0.1 on 2024-02-05 15:20

import uuid
from django.db import migrations, models
from django.core.management import call_command

def load_data(apps, schema_editor):
    call_command('loaddata', 'propriedades_seed.json')

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vinculos',
            fields=[
                ('idVinculo', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('idProdutor', models.UUIDField()),
                ('idPropriedade', models.UUIDField()),
            ],
            options={
                'db_table': 'Vinculos',
            },
        ),
        migrations.RunPython(load_data),
    ]
