# Generated by Django 5.0.1 on 2024-02-05 14:33

import uuid
from django.db import migrations, models
from django.core.management import call_command

def load_data(apps, schema_editor):
    call_command('loaddata', 'produtores_seed.json')

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produtores',
            fields=[
                ('idProdutor', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nomeProdutor', models.CharField(max_length=255)),
                ('registroIndividual', models.CharField(max_length=14)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'Produtores',
            },
        ),
        migrations.RunPython(load_data),
    ]
